import refrigeratorsImg from "../categories/refrigerators.png";
import audioImg from "../categories/audio.png";
import camerasImg from "../categories/cameras.png";
import cellPhoneEquipmentImg from "../categories/cell-phone-equipment.png";
import cellPhonesImg from "../categories/cell-phones.png";
import desktopsImg from "../categories/desktops.png";
import dronesImg from "../categories/drones.png";
import gameConsolesImg from "../categories/game-consoles.png";
import homeTeatherImg from "../categories/home-teather.png";
import laptopsImg from "../categories/laptops.png";
import microwavesImg from "../categories/microwaves.png";
import rangesCooktopsAndOvensImg from "../categories/ranges-cooktops-and-ovens.png";
import tabletsImg from "../categories/tablets.png";
import tvImg from "../categories/tv.png";
import videoGamesImg from "../categories/video-games.png";
import washingMashinesImg from "../categories/washing-mashines.png";

export const refrigerators = refrigeratorsImg;
export const audio = audioImg;
export const cameras = camerasImg;
export const cellPhoneEquipment = cellPhoneEquipmentImg;
export const cellPhones = cellPhonesImg;
export const desktops = desktopsImg;
export const drones = dronesImg;
export const gameConsoles = gameConsolesImg;
export const homeTeather = homeTeatherImg;
export const laptops = laptopsImg;
export const microwaves = microwavesImg;
export const rangesCooktopsAndOvens = rangesCooktopsAndOvensImg;
export const tablets = tabletsImg;
export const tv = tvImg;
export const videoGames = videoGamesImg;
export const washingMashines = washingMashinesImg;
